// Bundles the browser half of @vercel/blob into one committed file, because
// the app serves browser modules directly without a bundler.
// Rerun with `npm run build:vendor` after upgrading @vercel/blob.
import { build } from 'esbuild';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const { version } = JSON.parse(await readFile(new URL('../node_modules/@vercel/blob/package.json', import.meta.url)));
await build({
  stdin: { contents: "export { put } from '@vercel/blob/client';", resolveDir: root, loader: 'js' },
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  legalComments: 'none',
  banner: { js: `// Generated by scripts/build-vendor.js from @vercel/blob ${version}. Do not edit.` },
  outfile: fileURLToPath(new URL('../vendor/blob-client.js', import.meta.url))
});
console.log(`vendor/blob-client.js built from @vercel/blob ${version}`);
